BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[PartMaster] ALTER COLUMN [spec] NVARCHAR(1000) NULL;
ALTER TABLE [dbo].[PartMaster] ALTER COLUMN [dwg] NVARCHAR(1000) NULL;
ALTER TABLE [dbo].[PartMaster] ALTER COLUMN [dieNo] NVARCHAR(1000) NULL;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
